version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: evolution-postgres
    restart: always
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - AUTHENTICATION_API_KEY=9Kf@82Lm!xPq7Z#vA1ES
      - AUTHENTICATION_ENABLED=true
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_EXPOSE_IN_API=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/evolution
      - CONFIG_SESSION_PHONE_CLIENT=baileys
      - CONFIG_SESSION_PHONE_NAME=Ubuntu
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1038651499
      - CACHE_REDIS_ENABLED=false
    volumes:
      - evolution_evolution_data:/evolution

volumes:
  evolution_postgres_data:
  evolution_evolution_data:
