services:
  evolution-go:
    image: evoapicloud/evolution-go:latest
    container_name: evolution-go
    restart: unless-stopped
    ports:
      - "8082:8080"
    env_file:
      - .env
    networks:
      - evolution_default

networks:
  evolution_default:
    external: true
