services:
  evolution-go:
    image: evoapicloud/evolution-go:latest
    container_name: evolution-go
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - DB_TYPE=postgres
      - DB_HOST=evolution-postgres
      - DB_PORT=5432
      - DB_USER=postgres # Add your username
      - DB_PASSWORD=postgres # Add your password
      - DB_NAME=evolution_go
      - SERVER_PORT=8080
    networks:
      - evolution_default

volumes:
  evolution_postgres_data:

networks:
  evolution_default:
    external: true
